name       : nftables
version    : 0.9.0
release    : 1
source     :
    - https://netfilter.org/projects/nftables/files/nftables-0.9.0.tar.bz2 : ad8181b5fcb9ca572f444bed54018749588522ee97e4c21922648bb78d7e7e91
license    : GPL-2.0-only
component  : security
summary    : nftables replaces the popular iptables/ebtables
description: |
    This software provides a new in-kernel packet classification framework that is based on a network-specific Virtual Machine (VM) and a new nft userspace command line tool
builddeps  :
    - pkgconfig(libmnl)
    - pkgconfig(libnftnl)
    - pkgconfig(xtables)
    - docbook2x
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
