name       : nftables
version    : 1.0.7
release    : 6
source     :
    - https://www.netfilter.org/projects/nftables/files/nftables-1.0.7.tar.xz : c12ac941fff9adaedf17367d5ce213789b98a0d314277bc22b3d71e10891f412
license    : GPL-2.0-only
component  : security
homepage   : https://www.nftables.org/
summary    : nftables replaces the popular iptables/ebtables
description: |
    This software provides a new in-kernel packet classification framework that is based on a network-specific Virtual Machine (VM) and a new nft userspace command line tool
builddeps  :
    - pkgconfig(jansson)
    - pkgconfig(libmnl)
    - pkgconfig(libnftnl)
    - pkgconfig(python3)
    - pkgconfig(xtables)
    - docbook2x
setup      : |
    %patch -p1 < $pkgfiles/0001-Replace-distutils-with-setuptools.patch
    %configure \
        --disable-static \
        --with-json \
        --disable-debug \
        --with-cli=readline \
        --with-python-bin=/usr/bin/python3
build      : |
    # Prevent setuptools from installing an egg
    sed -i 's/--prefix $(DESTDIR)$(prefix)/--root $(DESTDIR) --prefix $(prefix)/' py/Makefile*

    %make
install    : |
    %make_install

    install -Dm00644 $pkgfiles/nftables.conf $installdir/etc/sysconfig/nftables.conf
    install -Dm00644 $pkgfiles/nftables.service $installdir/usr/lib/systemd/system/nftables.service
