name       : nftables
version    : 0.9.7
release    : 5
source     :
    - https://www.netfilter.org/projects/nftables/files/nftables-0.9.7.tar.bz2 : fe6b8a8c326a2c09c02ca162b840d7d4aadb043ce7a367c166d6455b0e112cb0
license    : GPL-2.0-only
component  : security
homepage   : https://www.nftables.org/
summary    : nftables replaces the popular iptables/ebtables
description: |
    This software provides a new in-kernel packet classification framework that is based on a network-specific Virtual Machine (VM) and a new nft userspace command line tool
builddeps  :
    - pkgconfig(jansson)
    - pkgconfig(libmnl)
    - pkgconfig(libnftnl)
    - pkgconfig(xtables)
    - docbook2x
setup      : |
    %configure \
        --disable-static \
        --with-json \
        --with-python-bin=/usr/bin/python3
build      : |
    %make
install    : |
    %make_install
